use std::fs;
use std::path::Path;

use crate::error::Result;
use crate::registry::EntityRegistry;

pub fn write_entity_registry(
    entity_registry_path: &Path,
    people: &[String],
    projects: &[String],
    mode: &str,
) -> Result<()> {
    let registry = EntityRegistry::bootstrap(mode, people, projects);
    registry.save(entity_registry_path)
}

pub fn write_aaak_entities(
    aaak_entities_path: &Path,
    people: &[String],
    projects: &[String],
    mode: &str,
) -> Result<()> {
    let mut registry_lines = vec![
        "# AAAK Entity Registry".to_string(),
        "# Auto-generated by mempalace-rs init. Update as needed.".to_string(),
        String::new(),
        format!("Mode: {mode}"),
        String::new(),
        "## People".to_string(),
    ];

    for person in people {
        registry_lines.push(format!("  {}={person}", entity_code(person, 3)));
    }
    if people.is_empty() {
        registry_lines.push("  (none detected yet)".to_string());
    }

    registry_lines.push(String::new());
    registry_lines.push("## Projects".to_string());
    for project in projects {
        registry_lines.push(format!("  {}={project}", entity_code(project, 4)));
    }
    if projects.is_empty() {
        registry_lines.push("  (none detected yet)".to_string());
    }

    registry_lines.extend([
        String::new(),
        "## AAAK Quick Reference".to_string(),
        "  Symbols: ♡=love ★=importance ⚠=warning →=relationship |=separator".to_string(),
        "  Structure: KEY:value | GROUP(details) | entity.attribute".to_string(),
        "  Read naturally — expand codes, treat *markers* as emotional context.".to_string(),
    ]);

    fs::write(aaak_entities_path, registry_lines.join("\n"))?;
    Ok(())
}

pub fn write_critical_facts(
    critical_facts_path: &Path,
    people: &[String],
    projects: &[String],
    configured_rooms: &[String],
    wing: &str,
    mode: &str,
) -> Result<()> {
    let mut lines = vec![
        "# Critical Facts (bootstrap — will be enriched after mining)".to_string(),
        String::new(),
        "## People".to_string(),
    ];

    for person in people {
        lines.push(format!("- **{person}** ({})", entity_code(person, 3)));
    }
    if people.is_empty() {
        lines.push("- none detected yet".to_string());
    }

    lines.push(String::new());
    lines.push("## Projects".to_string());
    for project in projects {
        lines.push(format!("- **{project}**"));
    }
    if projects.is_empty() {
        lines.push("- none detected yet".to_string());
    }

    lines.extend([
        String::new(),
        "## Palace".to_string(),
        format!("Wing: {wing}"),
        format!("Rooms: {}", configured_rooms.join(", ")),
        format!("Mode: {mode}"),
        String::new(),
        "*This file will be enriched after mining.*".to_string(),
    ]);

    fs::write(critical_facts_path, lines.join("\n"))?;
    Ok(())
}

fn entity_code(value: &str, max_len: usize) -> String {
    let mut cleaned = value
        .chars()
        .filter(|ch| ch.is_ascii_alphanumeric())
        .collect::<String>()
        .to_ascii_uppercase();
    cleaned.truncate(max_len);
    while cleaned.len() < max_len {
        cleaned.push('X');
    }
    cleaned
}
