pub mod audit;
pub mod bootstrap;
pub mod compress;
pub mod config;
pub mod convo;
pub mod dedup;
pub mod dialect;
pub mod drawers;
pub mod embed;
pub mod embedding_runtime;
pub mod entity_detector;
pub mod error;
pub mod hook;
pub mod instructions;
pub mod knowledge_graph;
pub mod layers;
pub mod mcp;
pub mod miner;
pub mod model;
pub mod normalize;
pub mod onboarding;
pub mod palace;
pub mod palace_graph;
pub mod palace_read;
pub mod registry;
pub mod registry_runtime;
pub mod repair;
pub mod room_detector;
pub mod searcher;
pub mod service;
pub mod spellcheck;
pub mod split;
pub mod storage;

pub use config::AppConfig;
pub use error::{MempalaceError, Result};

pub const VERSION: &str = env!("CARGO_PKG_VERSION");
